"""edit document table

Revision ID: 1f3a0984f094
Revises: 967061e2d209
Create Date: 2026-04-24 00:43:33.069915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3a0984f094'
down_revision: Union[str, Sequence[str], None] = '967061e2d209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('file_type', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('collection_name', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.drop_column('documents', 'file_name')
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    op.add_column('documents', sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_column('documents', 'collection_name')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###
