"""add project_settings_history table

Revision ID: ba9dae41a106
Revises: 1f3a0984f094
Create Date: 2026-04-24 14:08:46.585441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba9dae41a106'
down_revision: Union[str, Sequence[str], None] = '1f3a0984f094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_settings_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('old_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_settings_history_id'), 'project_settings_history', ['id'], unique=False)
    op.create_index(op.f('ix_project_settings_history_project_id'), 'project_settings_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_settings_history_user_id'), 'project_settings_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_settings_history_user_id'), table_name='project_settings_history')
    op.drop_index(op.f('ix_project_settings_history_project_id'), table_name='project_settings_history')
    op.drop_index(op.f('ix_project_settings_history_id'), table_name='project_settings_history')
    op.drop_table('project_settings_history')
    # ### end Alembic commands ###
